Feat/4 좌석 선택 화면
uxplorerss/uxplorers-frontend pull request #38
Opened 2024-11-26 05:59 UTC by YangJJune

## Summary

좌석선택 화면을 일부 style을 제외하고 구현하였습니다.

## Description

좌석 선택에 대한 상태 관리는 완료되었으며, 이후 바텀시트 관련해서 별찬님이 제작해주면 완성할 수 있을듯합니다

2024-11-26 06:22 UTC, Turtle-Hwan approved these changes
고생하셨습니다 👍 

lint 오류만 잡아주시면 될 거 같아요

2024-11-26 06:22 UTC, Turtle-Hwan commented on src/routes/booking/seats/index.tsx
> +  const [seats, setSeats] = useState<seat[]>([]);
useState는 위에서 한 번에 모아두는 것이 보기 좋을 거 같습니다

2024-11-26 06:22 UTC, Turtle-Hwan commented on src/routes/booking/seats/index.tsx
> +  const [seats, setSeats] = useState<seat[]>([]);
현재는 선택된 좌석 정보가 setSeats에 배열 형태로 저장되는 것 까지만 되어 있는거죠?? 따로 다른 페이지로 넘길 때 이 정보를 받아온다고 생각하면 될까요?

2024-11-26 06:42 UTC, YangJJune commented on src/routes/booking/seats/index.tsx
> +  const [seats, setSeats] = useState<seat[]>([]);
네 저기에 근데 아마 중고등 / 아이 / 어른 정보 넣고 넘기는게 가장 좋아보입니다. 다른 의견 있나요?

2024-11-26 06:42 UTC, Turtle-Hwan commented on src/routes/booking/seats/index.tsx
> +  const [seats, setSeats] = useState<seat[]>([]);
아뇨 현재 방식 좋습니다!

2024-11-26 09:28 UTC, algoORgoal requested changes
수고하셨습니다. 
리뷰한 것들 중에 다음은 필수로 해야할 것 같아요.
1. handleSelectSeat, onSelectSeat 맞추고 {...props} 해당 함수를 직접 사용하지 않는 컴포넌트는 {...props} 로 넘기기
2. useEffect 제거하여 리팩토링
3. lint 오류 해결

이외의 것들은 사소한 코드 스타일 차이로 인해 발생하는 차이라 나중에 고쳐도 될 것 같습니다.
그런데, 1/2/3은 안 쓰는 interface 숨기기/상태 추적/위험한 코드 제거로 꽤 중요한 부분을 차지할 거 같습니다.

수정 부탁드리겠습니다.
혹시 수정 사항이 너무 많다면 같이 나눠서 해도 됩니다.

2024-11-26 09:28 UTC, algoORgoal commented on src/common/Seats/RemainSeat/index.tsx
> +import refreshIcon from '../../../assets/refresh.svg';
import refreshIcon '../../../assets/refresh.svg?react' 로 경로 변경하면 리액트 컴포넌트마냥 사용할 수 있습니다.

2024-11-26 09:28 UTC, algoORgoal commented on src/common/Seats/RemainSeat/index.tsx
> +      <img src={refreshIcon}></img>
?react 쓰면 <RefreshIcon/>으로 바꿔서 쓸 수 있어요. 일관적으로 아이콘 통일하는 게 어떨까요?

2024-11-26 09:28 UTC, algoORgoal commented on src/common/Seats/RemainSeat/types.ts
> +export type SeatVariant = 'OCCUPIED' | 'SELECTED' | 'NORMAL' | 'NONE';
값이 고정된 변수의 이름에 대문자를 사용하는데, 스트링 안에 들어가는 값은 상수가 아니라 lowercase로 작성하는 게 readability를 높일 수 있을 것 같기는 해요.(제안)

2024-11-26 09:28 UTC, algoORgoal commented on src/common/Seats/Seat/index.tsx
> +          css={css`
css object 형태로 맞추는 게 어때요? 그렇게 한다면 typescript type error로 잡아줄 수가 있어요.

2024-11-26 09:28 UTC, algoORgoal commented on src/common/components/Seat/index.tsx
> +  const seatClickHandler = () => {
function name을 convention에 따라 handleClick으로 바꾸는 건 어때요?

onClick 파라미터 => handleClick을 넣어줌
onSelectSeat 파라미터 => handleSelectSeat을 넣어줌

2024-11-26 09:28 UTC, algoORgoal commented on src/common/components/Seat/index.tsx
> +            seatClickHandler();
onClick={handleClick}으로 함수명을 그대로 넘겨버리면 될 거 같습니다.

2024-11-26 09:28 UTC, algoORgoal commented on src/common/Seats/SelectSeat/index.tsx
> +                  key={index}
index를 key로 쓰는 것은 피하는 게 좋은데, seats 배열에 있는 아이템이 삭제/추가되지만 않는다면 렌더링 성능에 영향을 미치지는 않아 지금 상황에서는 괜찮을 거 같습니다.

예)
index 1 => 1번 좌석
index 2 => 2번 좌석
index 3 => 3번 좌석 
...
index 100 => 100번 좌석

여기서 index 1번 빠지면, index 1번으로 2번 좌석, index 2로 3번 좌석이 매핑되어 모든 배열 요소 리렌더링 발생.

@Turtle-Hwan 확인 부탁드립니다

2024-11-26 09:28 UTC, algoORgoal commented on src/main.tsx
> -    <StrictMode>
side effect가 없는지 확인하기 위해 StrictMode를 두는 게 더 나은 선택이라고 생각해요.
Strict 렌더링 횟수에 따라서 렌더링 결과가 달라져버리는지 아닌지 확인하는 좋은 방법이라고 생각합니다.

@Turtle-Hwan @YongChanCho 확인 부탁드립니다.

2024-11-26 09:28 UTC, algoORgoal commented on src/common/Seats/SeatType/index.tsx
> +const SeatType = () => {
현재 유지하고 있는 코드 스타일이
export defafult function SeatType(){
}
인데, 일관성을 위해 해당 스타일으로 짜는 게 좋을 거 같아요.

2024-11-26 09:28 UTC, algoORgoal commented on src/routes/booking/seats/index.tsx
> +      <SelectSeat seats={seats} seatClickHandler={seatClickHandler} />
seatClickHandler={seatClickHandler}를 
onSelectSeat={handleSelectSeat}으로 바꾸고, SelectSeat 컴포넌트에서는 그저 {...props} onSelectSeat 핸들러를 넘겨주는 식으로 짜는 건 어떤가요? 그 이유는 다음과 같습니다.
- react 자체의 네이밍 컨벤션(on and handle)
  - 인터렉션과 관련된 함수의 parameter의 이름을 on + (event 동사 이름)으로 규정
  - 해당 파라미터에 넘겨주는 인자 함수의 이름은 handle + (event 동사 이름)으로 규정
  
- 중간자 컴포넌트에서는 함수를 사용하지 않으므로 추가적으로 () => { onSelect(num) } 형태로 넘겨줄 필요가 없음. 해당 컴포넌트에서는 onSelect에 대한 디테일을 숨겨야 SOLID 원칙 중 인터페이스 분리 원칙을 만족하는 것으로 볼 수 있음(자신이 사용하지 않는 인터페이스는 구현하지 않기)
- 최종적으로 받는 곳에서는 handleClick은 해당 클릭을 할 때 seat num을 넘겨주는 것으로 추상화

2024-11-26 09:28 UTC, algoORgoal commented on src/routes/booking/seats/index.tsx
> +  const seatClickHandler = (num: number) => {
여기를 handleSelectSeat으로 이름 변경하는 것을 제안합니다.

2024-11-26 09:28 UTC, algoORgoal commented on src/routes/booking/seats/index.tsx
> +  useEffect(() => {
해당 useEffect는 필요가 없을 것 같아요. useState(initSeats())로 상태를 정의할 때 initialize를 할 수 있을 것 같습니다. 대신 iniSeats()에서 seats를 반환하는 형태로 가면 될 것 같습니다.

2024-11-26 09:28 UTC, algoORgoal commented on src/routes/booking/seats/index.tsx
> +    setAvailable(
현재 사용 가능한 좌석인 avaialable seats는 오직 seats 값으로부터 filter를 통해 구해지는 값이므로 상태가 아닌 const variable로 정의할 수 있다고 봅니다. useEffect가 늘어날 수록 상태 추적이 힘들어져서 useEffect를 안 쓰는 방향으로 가야 동작 예측이 쉬워진다고 생각합니다.

2024-11-26 09:38 UTC, Turtle-Hwan commented on src/common/Seats/SelectSeat/index.tsx
> +                  key={index}
오 되게 잘 잡아주셨네요! 동의합니다.

다만 한 번 렌더링 동안에 seats 배열이 바뀌는 것이 아닌 것이 보장되어 있으므로,
현재는 문제 없어 보입니다.

현재는 seats가 상태로 관리 중이므로 seats가 변경되면 해당 컴포넌트 전체가 리렌더링되고, map도 다시 배치될 것이라 index가 도중에 바뀌진 않을 거 같습니다

2024-11-26 09:39 UTC, Turtle-Hwan commented on src/main.tsx
> -    <StrictMode>
저도 동의합니다. StrictMode는 순수함수인지 확인하기 좋아서 유지하는 것이 나아 보여요!

2024-11-26 09:40 UTC, Turtle-Hwan commented on src/routes/booking/seats/index.tsx
> +  useEffect(() => {
오 그러네요 저도 알아갑니다

2024-11-28 07:28 UTC, YangJJune commented on src/common/Seats/SelectSeat/index.tsx
> +                  key={index}
저도 현재로서는 seats가 고정이라 괜찮다고 생각하고, 이를 감안하여 적용하였습니다
그리고 현재 seats가 중간에 비워놓는 걸 -1이라는 값을 주어 관리합니다.
따라서 key에 쓸 값이 없어 index를 적용하였습니다.

2024-11-28 07:29 UTC, YangJJune commented on src/main.tsx
> -    <StrictMode>
이거 직전에 한 해커톤에서 React.Strictmode로 JWT 토큰 생성 호출을 2번하면서 문제가 생겨 이걸 지워 해결했던 기억으로 습관적으로 지워버렸었습니다. 복구해놓겠습니다

2024-11-28 07:42 UTC, YangJJune commented on src/routes/booking/seats/index.tsx
> +  useEffect(() => {
이런 문법이 가능하군여

2024-11-28 07:49 UTC, YangJJune commented on src/routes/booking/seats/index.tsx
> +    setAvailable(
조금 이해가 되지 않습니다.
seats의 상태가 바뀌면, available의 상태가 바뀌기 때문에 useEffect를 사용하여 트리거가 일어나면 갱신해주려고 했던 것입니다. 사용자의 상호작용에 따라 결과값이 바뀌는 건 state로 지정하지 않고 할 수 있나요?
조언 바랍니다

2024-11-30 06:10 UTC, algoORgoal commented on src/routes/booking/seats/index.tsx
> +    setAvailable(
> 조금 이해가 되지 않습니다. seats의 상태가 바뀌면, available의 상태가 바뀌기 때문에 useEffect를 사용하여 트리거가 일어나면 갱신해주려고 했던 것입니다. 사용자의 상호작용에 따라 결과값이 바뀌는 건 state로 지정하지 않고 할 수 있나요? 조언 바랍니다

<img width="387" alt="image" src="https://github.com/user-attachments/assets/ddb9e3e7-1275-49c1-861a-33041eebce91">
해당 이미지와 같이 좌석을 선택할 때마다 잔여 좌석이 줄어들면 정상인가요?

2024-11-30 06:12 UTC, algoORgoal commented on src/routes/booking/seats/index.tsx
> +    setAvailable(
```ts
const available = seats.filter((value) => value.status === 'NORMAL').length;
```
선택한 좌석을 잔여 좌석에 포함시키지 않도록 수정하면, 잔여 좌석에 status가 SELECTED인 seat은 포함되지 않아 줄어들게 됩니다.

2024-11-30 06:13 UTC, algoORgoal commented on src/routes/booking/seats/index.tsx
> +    setAvailable(
제가 이해하기로는 잔여좌석(available)은 state가 아닙니다. seats 상태로부터 연산을 통해 구할 수 있는 값이기 때문입니다.

2024-11-30 06:20 UTC, algoORgoal commented on src/routes/booking/seats/index.tsx
> +    setAvailable(
1.  코드가 줄어든다.
2. 렌더링 횟수가 줄어들어 더 빨라진다.

따라서 저는 seats를 variable로 사용하는 것이 좋을 거라 판단했습니다.

> When something can be calculated from the existing props or state, [don’t put it in state.](https://react.dev/learn/choosing-the-state-structure#avoid-redundant-state) Instead, calculate it during rendering. This makes your code faster (you avoid the extra “cascading” updates), simpler (you remove some code), and less error-prone (you avoid bugs caused by different state variables getting out of sync with each other). If this approach feels new to you, [Thinking in React](https://react.dev/learn/thinking-in-react#step-3-find-the-minimal-but-complete-representation-of-ui-state) explains what should go into state.

https://react.dev/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state

2024-11-30 10:39 UTC, YangJJune commented on src/routes/booking/seats/index.tsx
> +    setAvailable(
아 코드에 실수가 있었군요...
그렇다면 오히려 이해가 잘 됩니다. 이게 안되니까 더더욱 헷갈렸던 부분이라
감사합니다

2024-11-30 15:52 UTC, algoORgoal approved these changes

2024-11-30 15:53 UTC, algoORgoal commented
결제하기 탭만 아래 추가하셨으면 merge하셔도 괜찮겠습니다.

2024-11-30 15:54 UTC, algoORgoal commented
아니면 그 부분 적용하는 부분은 새로 branch로 만들수도 있겠네요

2024-12-03 05:15 UTC, merged